### ISSUE TITLE
Exception creating a model when column type is tinyint

### ISSUE THREAD

**Issue by gwgrubbs** [HatTrickLabs/model#10]
When a column has a datatype specification of "TINYINT", the following exception occurs trying to build a model:

at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HatTrick.DbEx.Tools.Builder.TypeModelBuilder.CreateTypeModel(SqlDbType sqlType, String clrTypeOverride, Boolean isNullable, Boolean isEnum) in /home/vsts/work/1/s/tools/HatTrick.DbEx.Tools/Builder/TypeModelBuilder.cs:line 74
   at HatTrick.DbEx.Tools.Builder.DatabaseModelBuilder.CreateModel(MsSqlModel database, CodeGenerationHelpers helpers)

**Comment by JRod-Eiman** [comment]
Closing issue.  The culprit was actually within a model wrapper class within dbex tools.   Issue resolved within the other project.
